export const SET_NOTIFICATION_MESSAGE = 'SET_NOTIFICATION_MESSAGE'
export const SET_SHOW_NOTIFICATION_MESSAGE = 'SET_SHOW_NOTIFICATION_MESSAGE'
export const SET_SHOW_NOTIFICATION_POPUP_CARD = 'SET_SHOW_NOTIFICATION_POPUP_CARD'
export const SET_NOTIFICATION_SEVERITY = 'SET_NOTIFICATION_SEVERITY'